syntax = "proto3";

package catalog.v1;

option go_package = "github.com/repeter513/shop-proto/gen/go/catalog/v1;catalogv1";

import "google/protobuf/timestamp.proto";


service CatalogService {
  rpc GetProduct(GetProductRequest) returns (GetProductResponse);
  rpc ListProducts(ListProductsRequest) returns (ListProductsResponse);
  rpc ListCategories(ListCategoriesRequest) returns (ListCategoriesResponse);
  rpc GetStock(GetStockRequest) returns (GetStockResponse);
  rpc ReserveStock(ReserveStockRequest) returns (ReserveStockResponse);
  rpc ReleaseStock(ReleaseStockRequest) returns (ReleaseStockResponse);
  rpc ConfirmReservation(ConfirmReservationRequest) returns (ConfirmReservationResponse);
}


enum  ReservationStatus {
  RESERVATION_STATUS_UNSPECIFIED = 0;
  RESERVATION_STATUS_PENDING = 1;
  RESERVATION_STATUS_CONFIRMED = 2;
  RESERVATION_STATUS_RELEASED = 3;
  RESERVATION_STATUS_EXPIRED = 4;
}

message  Reservation {
  string reservation_id = 1;
  int64 order_id = 2;
  int64 product_id = 3;
  int32 quantity = 4;
  ReservationStatus status = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp expires_at = 7;
}

message Product {
  int64 id = 1;
  string name = 2;
  string description = 3;
  int64 price = 4;
  int64 category_id = 5;
  bool  active = 6;
}

message Category {
  int64 id = 1;
  string name = 2;
  int64 parent_id = 3;
}

message Stock {
  int64 product_id = 1;
  int32 quantity = 2;
}

message GetProductRequest {
  int64 product_id = 1;

}
message GetProductResponse {
  Product product = 1;
}
message ListProductsRequest {
  int32 page = 1;
  int32 page_size = 2;
  int64 category_id = 3;
}
message ListProductsResponse {
  repeated Product products = 1;
  int32 total_count = 2;
}
message ListCategoriesRequest {

}
message ListCategoriesResponse {
  repeated Category categories = 1;
}
message  GetStockRequest {
  int64 product_id = 1;
}
message GetStockResponse {
  Stock stock = 1;
}
message  ReserveStockRequest {
  int64 product_id = 1;
  int32 quantity = 2;
  int64 order_id = 3;
  string idempotency_key = 4;
}
message ReserveStockResponse {
  Reservation reservation = 1;
}
message ReleaseStockRequest {
  string reservation_id = 1;
}
message ReleaseStockResponse {
  Reservation reservation = 1;
}

message ConfirmReservationRequest {
  string reservation_id = 1;
}

message ConfirmReservationResponse {
  Reservation reservation = 1;
}

