syntax = "proto3";

import "google/protobuf/timestamp.proto";

package events.v1;

option go_package = "github.com/repeter513/shop-proto/gen/go/events/v1;events1";


enum ORDER_EVENT_TYPE {
  ORDER_EVENT_TYPE_UNSPECIFIED = 0;
  ORDER_EVENT_TYPE_PAID = 1;
  ORDER_EVENT_TYPE_FAILED = 2;
}
message OrderEvent {
  ORDER_EVENT_TYPE type = 1;
  int64 order_id = 2;
  int64 user_id = 3;
  double total_price = 4;
  int64 payment_id = 5;
}
enum NotificationChannel {
  NOTIFICATION_CHANNEL_UNSPECIFIED = 0;
  NOTIFICATION_CHANNEL_EMAIL = 1;
}
enum NotificationStatus {
  NOTIFICATION_STATUS_UNSPECIFIED = 0;
  NOTIFICATION_STATUS_SENT = 1;
  NOTIFICATION_STATUS_FAILED = 2;
}
message Notification{
  int64 id = 1;
  int64 user_id = 2;
  NotificationChannel channel = 3;
  string subject = 4;
  string body = 5;
  NotificationStatus status = 6;
  google.protobuf.Timestamp sent_at = 7;
}

